Repository ajktown/wordnote, pull requests merged in 2023-11, with the labels that each got.

#119 Refresh Bug
  src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
Labels: Bug

#124 Delete Script
  scripts/push-to-ecr.sh
Labels: refactor

#126 On Click Refresh Performance
  src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
  src/hooks/preference/use-preference.hook.ts
  src/hooks/words/use-words-with-semesters.hook.ts
Labels: performance
