Repository ajktown/wordnote, pull requests merged in 2023-10, with the labels that each got.

#105 Archive feature for word
  src/api/words/interfaces/index.ts
  src/atoms/StyledSwitch.tsx
  src/components/atom_language_selector/index.tsx
  src/components/atom_word_card_parts/index.archive-button.tsx
  src/components/atom_word_card_parts/index.unarchive-button.tsx
  src/components/atom_word_cards_frame_parts/index.archive-mode.tsx
  src/components/atom_word_cards_frame_parts/index.archive-switch.tsx
  src/components/molecule_new_word_box/index.tsx
  src/components/molecule_word_card/index.tsx
  src/components/organism_word_card_frame/index.tsx
  src/hooks/words/use-put-word-archive.hook.ts
  src/hooks/words/use-put-word-cache-by-key.hook.ts
  src/hooks/words/use-put-word-favorite.hook.ts
  src/hooks/words/use-put-word-tag-added.hook.ts
  src/hooks/words/use-put-word-tag-deleted.hook.ts
  src/hooks/words/use-put-word.hook.ts
  src/lambdas/parse-input-into-word.lambda.ts
  src/recoil/preferences/preference.state.ts
Labels: enhancement

#114 Fix the file name
  src/atoms/StyledDropDown.tsx
  src/atoms/StyledInputBase.tsx
Labels: refactor

#115 Yarn Latest Oct 2023
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#101 Dictionary based on NativeLanguages data of Preference
  src/api/preferences/get-preferences.api.ts
  src/api/preferences/index.interface.ts
  src/api/preferences/put-preference.api.ts
  src/components/atom_language_selector/index.tsx
  src/components/atom_preference_language_checkbox/index.tsx
  src/components/atom_tag_button/index.language.tsx
  src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
  src/components/dialog_preference/index.tsx
  src/components/molecule_dict_link_button_chunk/ja-ko-naver.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/ko-ja-naver.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/ko-naver.dict-link-button.tsx
  src/global.constants.ts
  src/hooks/preference/use-preference.hook.ts
  src/hooks/preference/use-put-preference-native-language.hook.ts
  src/hooks/preference/use-put-preference.hook.ts
  src/recoil/preferences/preference.state.ts
Labels: enhancement
