Repository ajktown/wordnote, pull requests merged in 2023-08, with the labels that each got.

#67 Beta warning
  src/hooks/words/use-post-word.hook.ts
  src/pages/welcome/index.tsx
Labels: enhancement

#66 Random Index Selectable with Surfing Icon
  src/components/atom_tag_button/index.semester.tsx
  src/components/atom_word_cards_frame_surfing_button/index.tsx
  src/hooks/semesters/use-semester-click.hook.ts
Labels: enhancement

#69 Dictionary buttons for languages
  .vscode/settings.json
  public/dictionary_icons/dictionary-dot-com.png
  public/dictionary_icons/naver-dictionary.png
  public/dictionary_icons/urban-dictionary.png
  src/atoms/StyledIconButton.tsx
  src/atoms/StyledImageButton.tsx
  src/components/molecule_dict_link_button_chunk/en-dictionary-dot-com.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/en-ko.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/en-urban-dictionary.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/index.tsx
  src/components/molecule_dict_link_button_chunk/ja-ko-naver.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/ko-naver.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/zh-ko-naver.dict-link-button.tsx
  src/components/molecule_word_card/index.tsx
  src/hooks/use-open-new-tab.ts
Labels: enhancement

#74 Surfing Icon Visible Only When User Has Three Or More Semesters
  src/components/atom_word_cards_frame_surfing_button/index.tsx
Labels: enhancement

#73 Post Word Card UX Improved
  README.md
  src/atoms/StyledTextField.tsx
  src/components/molecule_new_word_box/index.tsx
  src/components/molecule_tag_button_chunk/index.semesters.tsx
  src/global.interface.ts
  src/hooks/use-dynamic-focus.hook.ts
  src/hooks/words/use-post-word-with-string.hook.ts
Labels: enhancement

#77 fix: template
  .github/pull_request_template.md
Labels: Infra

#78 Template Removed
  .github/issue_template.md
  .github/pull_request_template.md
Labels: Infra

#79 Loading icons For Delete
  src/atoms/StyledTextButton.tsx
  src/components/atom_word_card_delete_button/index.tsx
  src/components/atom_word_card_undo_delete_button/index.tsx
  src/hooks/words/use-delete-word-cache.hook.ts
  src/hooks/words/use-delete-word.hook.ts
  src/hooks/words/use-post-word-from-undo.hook.ts
Labels: enhancement

#81 Hover Message for Surfing Icon
  src/components/atom_word_cards_frame_surfing_button/index.tsx
Labels: enhancement

#84 Optimized Dockerfile
  Dockerfile
Labels: Infra

#87 Link for Example
  src/api/words/interfaces/index.ts
  src/components/atom_word_card_confirm_modify_button/index.tsx
  src/components/atom_word_card_parts/index.example.tsx
  src/components/molecule_word_card/index.editing_mode.tsx
  src/components/molecule_word_card/index.tsx
  src/components/molecule_word_card_editing_text_field/index.tsx
  src/hooks/words/use-put-word-cache.hook.ts
  src/lambdas/parse-input-into-word.lambda.ts
Labels: enhancement

#88 Google Search Button
  public/dictionary_icons/google-dictionary.png
  src/components/molecule_dict_link_button_chunk/all-langs-google.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/index.tsx
Labels: enhancement

#86 Surfing Icon should expand semesters if clicked
  src/components/atom_word_cards_frame_surfing_button/index.tsx
Labels: enhancement

#90 Appropriate file name for selector
  src/components/atom_tag_button/index.all_semesters.tsx
  src/components/atom_tag_button/index.customized.tsx
  src/components/atom_tag_button/index.days_ago.tsx
  src/components/atom_tag_button/index.favorite.tsx
  src/components/atom_tag_button/index.language.tsx
  src/components/atom_tag_button/index.semester.tsx
  src/components/atom_word_cards_frame_surfing_button/index.tsx
  src/components/molecule_choose_semester/index.tsx
  src/components/molecule_tag_button_chunk/index.detailed.tsx
  src/components/organism_word_card_chunk/index.no_words_found.tsx
  src/hooks/words/use-put-word-favorite.hook.ts
  src/recoil/app/app.selectors.ts
  src/recoil/words/words.selectors.ts
Labels: refactor

#92 Example bug fix
  src/components/atom_word_card_parts/index.example.tsx
Labels: Bug

#93 Double Quote Bug for empty sample example
  src/components/atom_word_card_parts/index.example.tsx
Labels: Bug

#95 Same Variant for Example & ExampleLink
  src/components/atom_word_card_parts/index.example.tsx
Labels: enhancement

#97 Ko-Ja Dictionary for Japanese Natives
  src/components/molecule_dict_link_button_chunk/index.tsx
  src/components/molecule_dict_link_button_chunk/ko-ja-naver.dict-link-button.tsx
Labels: enhancement

#98 Preference with native language baseline code
  src/api/preferences/index.interface.ts
  src/components/atom_word_cards_frame_parts/index.preference-button.tsx
  src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
  src/components/atom_word_cards_frame_parts/index.surfing-button.tsx
  src/components/dialog_preference/index.tsx
  src/components/organism_word_card_frame/index.tsx
  src/hooks/ app/use-on-sign-out-app.hook.ts
  src/recoil/index.keys.ts
  src/recoil/preferences/preference.state.ts
Labels: enhancement

#100 Dummy data for preference state
  src/recoil/preferences/preference.state.ts
Labels: enhancement

#96 Yarn Latest Aug 2023
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency
