Repository ajktown/wordnote, pull requests merged in 2024-01, with the labels that each got.

#140 useIsAppBooted refactor
  src/hooks/ app/use-is-app-booted.hook.ts
Labels: refactor

#142 Review mode with meaning only
  src/components/atom_word_card_parts/index.example.tsx
  src/components/atom_word_cards_frame_parts/index.review-mode.tsx
  src/components/molecule_word_card/index.review_mode.tsx
  src/components/molecule_word_card/index.tsx
  src/components/organism_word_card_frame/index.tsx
  src/hooks/words/use-put-word-tag-added.hook.ts
  src/recoil/preferences/preference.state.ts
Labels: enhancement

#143 Review mode peek feature
  src/atoms/StyledVisibility.tsx
  src/components/atom_word_cards_frame_parts/index.review-mode.tsx
  src/components/molecule_word_card/index.review_mode.tsx
Labels: enhancement

#144 Refresh Button Bug with Latest Semester Not Automatically Selected
  src/hooks/words/use-words-with-semesters.hook.ts
Labels: Bug

#145 Hidden character removed for directory src/hooks/app
  src/components/atom_user_avatar/index.end-user.tsx
  src/hooks/app/use-is-app-booted.hook.ts
  src/hooks/app/use-on-sign-out-app.hook.ts
  src/hooks/use-api-error.hook.ts
  src/pages/_app.tsx
Labels: refactor

#141 Top of Page Button
  src/components/atom_top_of_page_button/index.tsx
  src/components/organism_word_card_chunk/index.tsx
Labels: enhancement

#149 Kubernetes like issue for wordnote fe
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/dependency.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/infrastructure.yaml
  .github/ISSUE_TEMPLATE/performance.yaml
  .github/ISSUE_TEMPLATE/refactor.yaml
Labels: documentation

#147 Edit Word during Review Mode
  src/components/molecule_word_card/index.review_mode.tsx
Labels: enhancement

#148 Question Mark for Disabled Icons with Hover Message
  src/atoms/StyledIconButton.tsx
Labels: enhancement

#146 openssf best practices like Kubernetes
  README.md
Labels: documentation

#152 Typo Fixed in Description of the Dependency of issue template
  .github/ISSUE_TEMPLATE/dependency.yaml
Labels: documentation

#151 Customize issue template to the ajktown wordnote based on k8s
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/dependency.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/infrastructure.yaml
  .github/ISSUE_TEMPLATE/performance.yaml
  .github/ISSUE_TEMPLATE/refactor.yaml
Labels: documentation

#155 Fix function name with on~ prefix
  src/components/molecule_word_card/index.tsx
Labels: refactor

#156 Undo Bug
  src/hooks/words/use-post-word-from-undo.hook.ts
Labels: bug

#157 Wordnote Frame with WordCards Count
  src/components/organism_word_card_chunk/index.tsx
Labels: enhancement

#159 Fix the Naming AtomTagButton => AtomTagChip
  src/atoms/StyledChip.tsx
  src/components/atom_tag_chip/index.all_semesters.tsx
  src/components/atom_tag_chip/index.customized.tsx
  src/components/atom_tag_chip/index.days_ago.tsx
  src/components/atom_tag_chip/index.deletable.tsx
  src/components/atom_tag_chip/index.expander.tsx
  src/components/atom_tag_chip/index.favorite.tsx
  src/components/atom_tag_chip/index.language.tsx
  src/components/atom_tag_chip/index.semester.tsx
  src/components/atom_word_card_add_tag_button/index.tsx
  src/components/molecule_tag_button_chunk/index.deletable.tsx
  src/components/molecule_tag_button_chunk/index.detailed.tsx
  src/components/molecule_tag_button_chunk/index.semesters.tsx
  src/components/molecule_tag_button_chunk/index.tsx
  src/components/organism_word_card_chunk/index.tsx
Labels: refactor

#135 Try Catch for Sign Out Flow
  src/hooks/app/use-on-sign-out-app.hook.ts
Labels: bug

#153 Yarn Latest Jan 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#158 Refactor hook naming convention and its usage
  src/atoms/StyledDropDown.tsx
  src/atoms/StyledIconButton.tsx
  src/components/atom_language_selector/index.tsx
  src/components/atom_tag_chip/index.all_semesters.tsx
  src/components/atom_tag_chip/index.customized.tsx
  src/components/atom_tag_chip/index.days_ago.tsx
  src/components/atom_tag_chip/index.deletable.tsx
  src/components/atom_tag_chip/index.favorite.tsx
  src/components/atom_tag_chip/index.language.tsx
  src/components/atom_word_ids_pagination/index.tsx
  src/components/molecule_appbar_search_bar/index.tsx
  src/components/molecule_dict_link_button_chunk/all-langs-google.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/en-dictionary-dot-com.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/en-ko.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/en-urban-dictionary.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/ja-ko-naver.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/ko-ja-naver.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/ko-naver.dict-link-button.tsx
  src/components/molecule_dict_link_button_chunk/zh-ko-naver.dict-link-button.tsx
  src/components/molecule_tag_button_chunk/index.deletable.tsx
  src/hooks/app/use-is-app-booted.hook.ts
  src/hooks/preference/use-preference.hook.ts
  src/hooks/semesters/use-apply-semester-details.ts
  src/hooks/semesters/use-semester-by-code.hook.ts
  src/hooks/semesters/use-semester-click.hook.ts
  src/hooks/semesters/use-semesters.hook.ts
  src/hooks/use-dynamic-focus.hook.ts
  src/hooks/use-handle-api-error.hook.ts
  src/hooks/use-key-press.hook.ts
  src/hooks/use-on-hover.hook.ts
  src/hooks/use-open-new-tab.ts
  src/hooks/use-outside-clicked.hook.ts
  src/hooks/use-refresh.hook.ts
  src/hooks/use-warning.hook.ts
  src/hooks/words/use-post-word.hook.ts
  src/hooks/words/use-put-word-favorite.hook.ts
  src/hooks/words/use-put-word-tag-added.hook.ts
  src/hooks/words/use-put-word-tag-deleted.hook.ts
  src/hooks/words/use-reset-search-input.hook.ts
  src/hooks/words/use-word-by-id.hook.ts
  src/hooks/words/use-word-ids.hook.ts
  src/hooks/words/use-words-with-semesters.hook.ts
  src/hooks/words/use-words.hook.ts
Labels: refactor

#113 Wordcard Share Feature Beta Phase 1: Smallest implementation Possible
  src/api/shared-resources/get-shared-resource.api.ts
  src/api/shared-resources/index.interface.ts
  src/api/shared-resources/post-shared-resource.api.ts
  src/api/words/interfaces/index.ts
  src/atoms/StyledChip.tsx
  src/atoms/StyledCountdownTimer.tsx
  src/components/atom_tag_chip/index.customized.tsx
  src/components/atom_tag_chip/index.language.tsx
  src/components/atom_word_card_parts/index.example.tsx
  src/components/atom_word_card_parts/index.share-button.tsx
  src/components/dialog_shared_resource/index.tsx
  src/components/molecule_tag_button_chunk/index.deletable.tsx
  src/components/molecule_tag_button_chunk/index.tsx
  src/components/molecule_word_card/index.share-review.tsx
  src/components/molecule_word_card/index.shared.tsx
  src/components/molecule_word_card/index.tsx
  src/components/organism_word_card_frame/index.tsx
  src/constants/page-queries.constant.ts
  src/constants/pages.constant.ts
  src/hooks/app/use-is-app-booted.hook.ts
  src/hooks/shared-resources/use-shared-resource.hook.ts
  src/organisms/StyledDialogLoading.tsx
  src/pages/share/index.tsx
  src/recoil/index.keys.ts
  src/recoil/shared-resource/shared-resource.state.ts
Labels: enhancement

#162 Hotfix Semester Looping Around
  src/hooks/words/use-words-with-semesters.hook.ts
Labels: bug

#163 refactor onSignOutApp function name
  src/hooks/app/use-is-app-booted.hook.ts
  src/hooks/use-handle-api-error.hook.ts
Labels: refactor

#167 refactor names of functionaries
  src/components/atom_word_card_add_tag_button/index.tsx
  src/components/atom_word_card_favorite_icon/index.tsx
  src/components/molecule_new_word_box/index.tsx
  src/components/organism_word_card_chunk/index.search_not_found.tsx
  src/hooks/preference/use-put-preference-native-language.hook.ts
  src/hooks/words/use-post-word-with-string.hook.ts
Labels: refactor

#170 Review Mode with More Action Buttons
  src/components/molecule_word_card/index.review_mode.tsx
Labels: enhancement

#171 DeepL Dictionary Button
  public/dictionary_icons/deepl.png
  src/components/molecule_dict_link_button_chunk/index.tsx
  src/components/molecule_dict_link_button_chunk/ja-en-deepl.dict-link-button.tsx
Labels: enhancement

#176 Singular format for one word card
  src/components/organism_word_card_chunk/index.tsx
Labels: enhancement
