Repository ajktown/wordnote, pull requests merged in 2024-03, with the labels that each got.

#194 Search dialog openable in WordCard
  src/components/atom_word_card_parts/index.search-this-word.tsx
  src/components/molecule_tag_button_chunk/index.tsx
  src/components/molecule_word_card/index.review_mode.tsx
  src/components/molecule_word_card/index.search_dialog.tsx
  src/components/molecule_word_card/index.share-review.tsx
  src/components/molecule_word_card/index.tsx
  src/components/organism_word_card_frame/index.tsx
  src/hooks/words/use-searched-words-by-word-id.hook.ts
  src/recoil/words/searchInput.state.ts
Labels: enhancement

#195 Yarn Latest March 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#196 EnterKey bug on conversion
  src/hooks/use-key-press.hook.ts
Labels: bug

#198 Dictionary icons not visible when window width not big enough (smartphone screens)
  src/components/molecule_dict_link_button_chunk/index.tsx
  src/components/molecule_tag_button_chunk/index.tsx
  src/components/molecule_word_card/index.review_mode.tsx
  src/components/molecule_word_card/index.tsx
Labels: bug

#201 Buy me coffee in README.md
  README.md
Labels: documentation

#203 Introduce dev_wordnote for developers of Wordnote
  README.md
Labels: documentation

#204 Appbar shrinks
  src/components/organism_appbar/index.tsx
  src/molecules/StyledAppbar.tsx
Labels: enhancement

#209 Yarn Latest Late March 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#205 Shared Word Card Page Visual Improvement
  src/components/organism_shared_word_card_frame/index.tsx
  src/pages/share/index.tsx
Labels: enhancement

#199 First buy me coffee
  src/components/atom_user_avatar/index.end-user.tsx
Labels: enhancement

#210 Implement `command + enter` for apply modification
  src/components/atom_word_card_confirm_modify_button/index.tsx
  src/components/molecule_new_word_box/index.tsx
  src/global.interface.ts
  src/hooks/use-key-press.hook.ts
Labels: enhancement
