Repository ajktown/wordnote, pull requests merged in 2024-02, with the labels that each got.

#175 Underscore during the review mode
  src/components/atom_word_card_parts/index.example.tsx
Labels: enhancement

#179 SearchInput searches is non-semester scoped
  src/components/atom_tag_chip/index.semester-code.tsx
  src/components/molecule_tag_button_chunk/index.tsx
  src/hooks/words/use-words.hook.ts
Labels: enhancement

#180 Search this word button
  src/components/atom_word_card_parts/index.search-this-word.tsx
  src/components/molecule_word_card/index.tsx
Labels: enhancement

#181 Yarn Latest Feb 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#183 Consistency Page is now open in beta. Wordnote should suggest users to go
  src/api/action-groups/get-action-groups.api.ts
  src/components/atom_appbar_parts/index.to_consistency_page_button.tsx
  src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
  src/hooks/action-groups/use-action-groups.hook.ts
  src/hooks/words/use-delete-word.hook.ts
  src/hooks/words/use-post-word-from-undo.hook.ts
  src/hooks/words/use-post-word.hook.ts
  src/lambdas/axios-request-success.lambda.ts
  src/lambdas/get-env.lambda.ts
  src/molecules/StyledAppbar.tsx
  src/recoil/action-groups/action-groups.state.ts
Labels: enhancement

#185 Handle API Change "Standardize Action Group and Action"
  src/api/action-groups/get-action-group-daily-post-word-challenge.api.ts
  src/api/action-groups/get-action-groups.api.ts
  src/api/action-groups/index.interface.ts
  src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
  src/constants/action-group.constant.ts
  src/hooks/action-groups/use-action-group-daily-post-word-challenge.api.ts
  src/hooks/words/use-delete-word.hook.ts
  src/hooks/words/use-post-word-from-undo.hook.ts
  src/hooks/words/use-post-word.hook.ts
Labels: enhancement

#182 No longer shows the ??? during review mode without double quotes
  src/components/atom_word_card_parts/index.example.tsx
Labels: enhancement

#186 Leave an indent for the last line
  .github/ISSUE_TEMPLATE/dependency.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/infrastructure.yaml
  .github/ISSUE_TEMPLATE/performance.yaml
  .github/ISSUE_TEMPLATE/refactor.yaml
Labels: documentation

#189 GitHub Icon
  src/components/atom_appbar_parts/index.github_icon.tsx
  src/molecules/StyledAppbar.tsx
Labels: enhancement

#192 Refactor usePostWord with returned value isLoading
  src/components/organism_word_card_chunk/index.search_not_found.tsx
  src/hooks/words/use-post-word-with-string.hook.ts
  src/hooks/words/use-post-word.hook.ts
Labels: refactor

#191 Shared Word Page now let users to download the word if signed in
  src/atoms/StyledIconButtonNewPage.tsx
  src/components/atom_shared_word_card_parts/index.add-word-button.tsx
  src/hooks/app/use-is-app-booted.hook.ts
  src/pages/share/index.tsx
Labels: enhancement
